apiVersion: apps/v1
kind: Deployment
metadata:
  name: ng-jen-kube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-jenkins-kube
  template:
    metadata:
      labels:
        app: nginx-jenkins-kube
    spec:
      containers:
      - name: nginx-test-container
        image: nginx:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
        - containerPort: 80
        
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-jenkins-kube-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx-jenkins-kube
    type: webserver
  ports:
  - port: 80
    targetPort: 80
